
version: '3.7'
services:
  frontend:
    container_name: frontend
    image: navid12/naveed
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
     - "3001:3000"
    environment:
     - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
     - backend
    restart: always
  
  backend:
    container_name: backend
    image: navid12/back
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
