version: '3.7'
services:
  frontend:
    container_name: my-app
    build:
      context: ./my-app
      dockerfile: dockerfile
    ports:
     - "3001:3000"
    environment:
     - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
     - backend
    restart: always
  
  backend:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8000:8000"